name: ublue main 40
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 10 * * *'  # 3pm UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  ublue-40:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 40