name: ublue main 39
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 15 * * *'  # 3pm UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  ublue-39:
    name: "build ublue-os/*-main:39"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 39